### ISSUE TITLE
iascable v2.17.3 install failling

### ISSUE THREAD

**Issue by NoeSamaille** [cloud-native-toolkit/iascable#203]
```sh
❯ curl -sL https://iascable.cloudnativetoolkit.dev/install.sh | RELEASE=2.17.3 DEST_DIR=~/bin sh

Installing version 2.17.3 of iascable for macos into /Users/noesamaille/bin
######################################################################## 100.0%
❯ iascable --version
/snapshot/iascable/dist/lib/commands/scripts/launch-script.js:49
SUFFIX=\$(echo \$(basename \${SCRIPT_DIR}) | base64 | sed -E "s/[^a-zA-Z0-9_.-]//g" | sed -E "s/.*(.{5})/\1/g")
                                                                                                          

SyntaxError: Octal escape sequences are not allowed in template strings.
    at Object.compileFunction (node:vm:354:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._compile (pkg/prelude/bootstrap.js:1937:32)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by NoeSamaille** [comment]
@triceam FYI
