### ISSUE TITLE
IasCable v3 breaking most tests, and iascable library import

### ISSUE THREAD

**Issue by NoeSamaille** [cloud-native-toolkit/iascable#267]
Git commit 49671c47c2d311f6b6527ebeca8272f453dae64c introduced most tests to fail:

```
$ git checkout 49671c47c2d311f6b6527ebeca8272f453dae64c
$ CI=true npm run test
...
Test Suites: 7 failed, 7 passed, 14 total
Tests:       71 passed, 71 total
Snapshots:   0 total
Time:        7.843 s
Ran all test suites.
error Command failed with exit code 1.                                                             
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.               
```

Also it's now impossible to import `@cloudnativetoolkit/iascable` as library in `.js` or `.ts` files, giving following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type function. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at inherits (node:util:239:11)
    at /Users/noesamaille/Documents/projects/starters/express-test/node_modules/@cloudnativetoolkit/iascable/dist/iascable.umd.js:37732:3
    at /Users/noesamaille/Documents/projects/starters/express-test/node_modules/@cloudnativetoolkit/iascable/dist/iascable.umd.js:2:66
    at Object.<anonymous> (/Users/noesamaille/Documents/projects/starters/express-test/node_modules/@cloudnativetoolkit/iascable/dist/iascable.umd.js:5:2)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by NoeSamaille** [comment]
@seansund tried to investigate but not sure where it's coming exactly

**Comment by NoeSamaille** [comment]
@seansund I have fixed the tests and released by installing the `memory-stream` package required in `src/util/file-util.ts` that was missing for some reason.

I have released [v3.0.0-beta.3](https://github.com/cloud-native-toolkit/iascable/releases/tag/v3.0.0-beta.3) but import error above is still there

**Comment by seansund** [comment]
@NoeSamaille For some reason there were a couple of dependencies that were missing from package.json but for some reason the CI build and test process was still passing.

I'll figure out why it isn't building

**Comment by seansund** [comment]
@NoeSamaille removed the memory-stream dependency and the issue was resolved
